# Generated by Django 3.0.4 on 2020-04-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacanies'},
        ),
    ]
