# Generated by Django 3.0.4 on 2020-04-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200418_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.Company'),
        ),
    ]
